import type { Portfolio } from '@/domain/models';
import { portfolioNameKey } from '@/domain/PortfolioName';

import { PrismaClient } from './PrismaClient';

/** Backs the unique index only: a response carries the name itself. */
const NAME_KEY_COLUMN = { nameKey: true } as const;

/**
 * Every lookup is filtered by the owner, so a portfolio id taken from a request
 * never reaches another user's portfolio.
 */
export class PortfolioRepository {
  private static INSTANCE: PortfolioRepository;
  private prismaClient: PrismaClient;

  private constructor() {
    this.prismaClient = PrismaClient.getInstance();
  }

  static getInstance() {
    if (!PortfolioRepository.INSTANCE)
      PortfolioRepository.INSTANCE = new PortfolioRepository();

    return PortfolioRepository.INSTANCE;
  }

  async getAll(params: PortfolioRepository.GetAllParams) {
    const { userId, page, limit } = params;

    const [total, docs] = await Promise.all([
      this.prismaClient.portfolio.count({ where: { userId } }),
      this.prismaClient.portfolio.findMany({
        where: { userId },
        omit: NAME_KEY_COLUMN,
        orderBy: [{ createdAt: 'asc' }, { id: 'asc' }],
        take: limit,
        skip: (page - 1) * limit
      })
    ]);

    return {
      docs,
      pagination: { page, total, limit, totalPages: Math.ceil(total / limit) }
    };
  }

  async getById(params: PortfolioRepository.GetByIdParams) {
    const { id, userId } = params;

    return this.prismaClient.portfolio.findFirst({
      where: { id, userId },
      omit: NAME_KEY_COLUMN
    });
  }

  /**
   * The unique index on the owner and the name key is the only authority on
   * whether the name is free, so of concurrent creations under one name exactly
   * one succeeds. The id is generated by Prisma for this row, so a violation
   * can only mean the name.
   */
  async add(
    params: PortfolioRepository.AddParams
  ): Promise<PortfolioRepository.AddOutcome> {
    try {
      return {
        outcome: 'created',
        portfolio: await this.prismaClient.portfolio.create({
          data: { ...params, nameKey: portfolioNameKey(params.name) },
          omit: NAME_KEY_COLUMN
        })
      };
    } catch (error) {
      if (PrismaClient.isUniqueConstraintViolation(error))
        return { outcome: 'name-taken' };

      throw error;
    }
  }

  /** A rename that keeps the key, a change of letter case, is the portfolio's own name and never collides. */
  async update(
    params: PortfolioRepository.UpdateParams
  ): Promise<PortfolioRepository.UpdateOutcome> {
    try {
      return await this.updateOwned(params);
    } catch (error) {
      if (PrismaClient.isUniqueConstraintViolation(error))
        return { outcome: 'name-taken' };

      throw error;
    }
  }

  private async updateOwned({
    id,
    userId,
    name,
    baseCurrency
  }: PortfolioRepository.UpdateParams): Promise<PortfolioRepository.UpdateOutcome> {
    return this.prismaClient.runSerializable(async (transactionClient) => {
      const portfolio = await transactionClient.portfolio.findFirst({
        where: { id, userId }
      });

      if (!portfolio) return { outcome: 'not-found' };

      const changesBaseCurrency =
        baseCurrency !== undefined && baseCurrency !== portfolio.baseCurrency;

      if (
        changesBaseCurrency &&
        (await transactionClient.transaction.count({
          where: { portfolioId: id }
        })) > 0
      )
        return { outcome: 'base-currency-locked' };

      return {
        outcome: 'updated',
        portfolio: await transactionClient.portfolio.update({
          where: { id },
          data: {
            name,
            nameKey: name === undefined ? undefined : portfolioNameKey(name),
            baseCurrency
          },
          omit: NAME_KEY_COLUMN
        })
      };
    });
  }

  async delete(
    params: PortfolioRepository.DeleteParams
  ): Promise<PortfolioRepository.DeleteOutcome> {
    const { id, userId } = params;

    return this.prismaClient.runSerializable(async (transactionClient) => {
      const portfolio = await transactionClient.portfolio.findFirst({
        where: { id, userId }
      });

      if (!portfolio) return { outcome: 'not-found' };

      const ownedPortfolios = await transactionClient.portfolio.count({
        where: { userId }
      });

      if (ownedPortfolios === 1) return { outcome: 'last-portfolio' };

      await transactionClient.transaction.deleteMany({
        where: { portfolioId: id }
      });
      await transactionClient.position.deleteMany({
        where: { portfolioId: id }
      });
      await transactionClient.portfolio.delete({ where: { id } });

      return { outcome: 'deleted' };
    });
  }
}

namespace PortfolioRepository {
  export type GetAllParams = Pick<Portfolio, 'userId'> &
    Record<'page' | 'limit', number>;
  export type GetByIdParams = Pick<Portfolio, 'id' | 'userId'>;
  export type AddParams = Pick<Portfolio, 'userId' | 'name' | 'baseCurrency'>;
  export type AddOutcome =
    | { outcome: 'created'; portfolio: Omit<Portfolio, 'positions'> }
    | { outcome: 'name-taken' };
  export type UpdateParams = GetByIdParams &
    Partial<Pick<Portfolio, 'name' | 'baseCurrency'>>;
  export type UpdateOutcome =
    | { outcome: 'updated'; portfolio: Omit<Portfolio, 'positions'> }
    | { outcome: 'not-found' }
    | { outcome: 'base-currency-locked' }
    | { outcome: 'name-taken' };
  export type DeleteParams = GetByIdParams;
  export type DeleteOutcome =
    | { outcome: 'deleted' }
    | { outcome: 'not-found' }
    | { outcome: 'last-portfolio' };
}
