import type { Metadata } from 'next';

import { QueryClientProvider } from '@tanstack/react-query';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import { Toaster } from 'sonner';

import { inter } from '@/common/constants';
import { UserProvider } from '@/hooks/use-user';
import { queryClient } from '@/lib/react-query';
import type { Children } from '@/types';
import './globals.css';

export const metadata: Metadata = {
  title: 'EX3',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: Readonly<Children>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider client={queryClient}>
          <ReactQueryDevtools initialIsOpen={false} />

          <Toaster richColors />

          <UserProvider>{children}</UserProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
