import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>EX3</title>

        <meta name="description" content="Generated by create next app" />

        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <span>Hello World</span>
      </main>
    </>
  );
}
